### ISSUE TITLE
Convert running mailcow

### ISSUE THREAD

**Issue by Paktosan** [Shadowghost/mailcow-mailman3-dockerized#1]
Hello,
today I tried to convert my running mailcow but failed. Can you give an explanation on how to do it?

**Comment by Shadowghost** [comment]
I'll write a little documentation if I have some time today.
In short you clone this repo, create the config file, copy the old values from your existing install, change the project name within .env back to mailcow-dockerized and run `docker-compose pull && docker-compose up -d`. Don't forget to shut down your existing containers before.

**Comment by Shadowghost** [comment]
Migration explanation is added. Keep in mind that this project is still somehow experimental and some things may not work.
