### ISSUE TITLE
createsuperuser failed

### ISSUE THREAD

**Issue by udoL** [Shadowghost/mailcow-mailman3-dockerized#11]
Hi,
tried an migration to mailcow-mailman3 from an fresh installation of mailcow.
createsuperuser failed:
`root@vmail01:/opt/mailcow-mailman3-dockerized# docker exec -it mailcowdockerized_mailman-web_1 /bin/bash

bash-4.4#  python manage.py createsuperuser
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management`
 `44353fab6e1f        maxking/mailman-web:latest    "docker-entrypoint.s…"   44 minutes ago      Up 12 minutes       8000/tcp, 0.0.0.0:8080->8080/tcp`
I've changed the IP-range (172.22.1) and create port-forwarding 8080 due my proxy is running on an external VM (haproxy).
I've read in an other issue, that mailman hardcoded the IP - perhaps i must reconfigure to 
172.19.199?

BTW: in line 29 of generate_config.sh is the last E missing: MAILCOW_HOSTNAM

Udo

**Comment by weingaertnerit** [comment]
docker exec -it mailcowdockerized_mailman-web_1 python3 manage.py createsuperuser

**Comment by Shadowghost** [comment]
Sorry guys, didn't get a notification for the issue.
What @markusblogde wrote should fix your problem. I pushed a fix for the typo in `generate_config.sh` and updated the repo to latest mailcow master. Sorry for the inconvenience.
