### ISSUE TITLE
Issue setting up project -- Networks have overlapping IPv4

### ISSUE THREAD

**Issue by roddarjohn** [Shadowghost/mailcow-mailman3-dockerized#3]
Hi, really excited about the potential for this project.

Commands run:
I first cloned the repo
`sudo bash generate_config.sh`
`sudo docker-compose pull && sudo docker-compose up -d`
The generated the following error:
`cannot create network <hash>: conflicts with network <hash>: networks have overlapping IPv4`

I thought the issue may have been with previous dockers conflicting network-wise.
I ran the following two commands before retrying the config to confirm:
`sudo docker stop $(sudo docker ps -a -q)`
`sudo docker rm $(sudo docker ps -a -q)`

Let me know if anything else would be helpful

**Comment by Shadowghost** [comment]
Yeah I needed to change the IPv4 network, since the used mailman3 images seem to have hardcoded IPs. That's why now it is hardcoded to 172.19.199.X and this will of course lead to problems with containers already in this IP-range.
You can try to restart docker `systemctl restart docker` after running `docker-compose down`, this will reset all IP addresses and routs reserved by docker, maybe it's just that simple.

**Comment by roddarjohn** [comment]
Just tried that.

I ran:
`sudo docker-compose down`
`sudo systemctl restart docker`
`sudo docker-compose pull && sudo docker-compose up -d`
Still running into the same issue.

**Comment by Shadowghost** [comment]
Do you have any other docker containers running? If the answer is yes, they may use the same IP-ranges as used in this project. Can't do anything in this case because of the hardcoded IPs in mailman.

**Comment by roddarjohn** [comment]
Yup, that fixed the problem.  Now the docker-compose up is running fine and everything starts, but if I navigate to the urls, there's no website.

The DNS is configured properly as it was working for mailcow.

**Comment by roddarjohn** [comment]
This may be because the configuration script was failing with `lstat /opt/mailcow-mailman3-dockerized/templates/mailman/core: no such file or directory`

**Comment by roddarjohn** [comment]
Ahh, didn't read to the end of the config, I need to setup Apache to proxy -- thanks for your help!

**Comment by Shadowghost** [comment]
Yeah but the Proxy seems to be broken atm. No idea why though, still debugging.
It's likely that I'll rebase the repo on the most recent mailcow master.

**Comment by roddarjohn** [comment]
Uh oh.

Looking forward to it being all integrated.

**Comment by Shadowghost** [comment]
Should work now. At least in my test environment everything seems to work. If any errors occurr, just open a new issue :)

Keep in mind, that you need to clone the repo again, since I rebased it (had some faulty commits).
