### ISSUE TITLE
Database Connection Issue

### ISSUE THREAD

**Issue by roddarjohn** [Shadowghost/mailcow-mailman3-dockerized#4]
After messing around with Apache2 modules, I got everything working, to be greeted by a database connection error.

<img width="796" alt="screen shot 2018-07-13 at 9 30 50 pm" src="https://user-images.githubusercontent.com/10851328/42719490-2319fcb2-86e4-11e8-9a9f-5f71ce223023.png">

There's likely some dumb setting that I forgot about, but it seems like this should be handled by the docker setup.

**Comment by Shadowghost** [comment]
Database settings for mailcow are handled by the following variables in your `.env` file:
```
# ------------------------------------
# Mailcow SQL database configuration
# ------------------------------------
MCDBNAME=mailcow
MCDBUSER=mailcow
# Please use long, random alphanumeric strings (A-Za-z0-9)
MCDBPASS=
MCDBROOT=
```

If you moved your installation from an existing mailcow install, keep in mind that the variable's name changed from `DBPASS` to `MCDBPASS` and from `DBROOT` to `MCDBROOT`.

You can also check the docker logs with `docker-compose logs -f mysql-mailcow`.

**Btw:** I don't have this problems on a fresh setup.

**Comment by roddarjohn** [comment]
Problem was fixed by reinstalling docker and docker-compose—there were hanging images.

**Comment by Shadowghost** [comment]
Nice to hear, that you've figured it out :)
