### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by roddarjohn** [Shadowghost/mailcow-mailman3-dockerized#5]
If I go to mail.<domain> I can see and login to the mailcow UI, as well as SoGO.

Upon going to lists.<domain> I see a 400 Bad Request.  There is nothing in error.log for Apache regarding the issue, so it's probably something with Postorius and how it is handling.

Any thoughts / where would the Postorius / Django logs be to see if I can debug it.

EDIT:
Upon running the createsuperuser command, I get the following error:

`No such container: mailman-web` — maybe something didn't create properly?

**Comment by Shadowghost** [comment]
Everything went fine, I just need to change that command to `docker exec -it <your-project-name>_mailman-web python manage.py createsuperuser` in the readme.
Besides that you should not get a `Error 400` at all, seems like a configuration error. You canc check some things:
* Did you change `example.org`in the example configs to your domain?
* Make sure you've replaced `<path-to-repo>`with the correct path (I missed writing it in the block for port 80)
* Make sure `mailman-core` and `mailman-web` did fully initialize the database and run their migrations (mailman-web needs some time to do that). Check with `docker-compose logs -f mailman-web`
* Check if you've installed the needed apache2 modules and if you've enabled the site configuration with `a2ensite lists.conf` and reloaded apache config afterwards

**Comment by roddarjohn** [comment]
In order:
<img width="316" alt="screen shot 2018-07-14 at 9 54 30 am" src="https://user-images.githubusercontent.com/10851328/42725070-eedf2db0-874b-11e8-8898-6c5be1f37140.png"> is from `.env`.  So I tried running the Django management command again and it gave me `Error: no such container: mailcowdockerized_mailman-web`.

- I did change the `example.org`s so I don't think that's it.
- I see what you mean in the port 80 section, I changed those to reflect the correct directory `<path-to-repo>/data/mailman/web/static` for example
- The logs for `mailman-web` indicated that it did run the migration script but that there was nothing to migrate (probably because I've restarted the docker once or twice as a sanity check).  The only thing in the logs for `mailman-core` is that there's no MTA set by default, so it defaulted to Exim which should be fine as well as the `HYPERKITTY_URL` wasn't set but that shouldn't matter, and MySQL started properly.
- I enabled all the modules including uwsgi, proxy, proxy_html, etc, and the site is enabled.  I'm also pretty sure if the modules weren't enabled, Apache would throw and error which it isn't.

Thoughts?

**Comment by roddarjohn** [comment]
I got the Django command to work, the correct docker container name is:
`<your-project-name>_mailman-web_1` when it is creating, it prints the name as `<your-project-name>_mailman-web-1` but when you run `docker container ls` the dash becomes an underscore...

**Comment by Shadowghost** [comment]
Yeah I remembered that when reading your answer right now. ` Error 400` without any thing in the Apache logs isn't really helping :/
If I come up with something else to try, I'll post it :)

**Comment by roddarjohn** [comment]
I'll keep working on it as well and will post if I figure anything out.

Thanks much!

**Comment by roddarjohn** [comment]
Problem solved after combing through the Django logs:

I was entering the url for Mailman3 as `lists.<domain>` as I wanted the lists to be at a subdomain.  The configuration scripts for the Django wsgi prepended another `lists.` to the entered domain, thus it was serving at `lists.lists.<domain>`.  Wiping all dockers, reinstalling with correct configuration fixed the bad request problem.

**Comment by Shadowghost** [comment]
Nice to hear, you've figured it out. Should I add something to the documentation regarding this?

**Comment by roddarjohn** [comment]
Yes certainly, I'll have some time tonight and will add some documentation as well.  I'm still struggling with one last piece of this, but I'll create a new issue.
