### ISSUE TITLE
Mailman List Addresses not Found

### ISSUE THREAD

**Issue by roddarjohn** [Shadowghost/mailcow-mailman3-dockerized#6]
Everything is setup, I can access both sites `mail.<domain>` and `lists.<domain>`.  The issue now is that Mailman is not receiving mail.  It sends mail (if I add a user, the user gets an email) but when I send an email back to the email address listed in the subscription email, it bounces.

I first tried entering the mail host as `<domain>` but then noticed that the emails were being sent from `Postorius@lists.<domain>` so I deleted it and started a list with the mail host as `lists.<domain>` but that didn't work.  To complete the guessing, I also tried `mail.<domain>` but it still wasn't receiving mail (the bounce error changed each time though, let me know if posting that would be helpful.

The screen that I'm referring to when I saw entering the mail domain is this one:
<img width="1110" alt="screen shot 2018-07-14 at 3 40 12 pm" src="https://user-images.githubusercontent.com/10851328/42727883-430ed4b4-877c-11e8-87cf-057dc754048f.png">

**Comment by Shadowghost** [comment]
Just for completion: Mailman lists work like that:
Your webinterface is hosted on `lists.example.org`. Now you create the domain `example.org` with the webhost `lists.example.org`. After that you create a list `test` with the mailhost `example.org`. Now you can subscribe the list by sending an mail to `test-join@example.org` with `subscribe` as subject. After your subscription is approved, you can send mails to the list with `test@example.org` as reciever.

**Comment by roddarjohn** [comment]
Thanks for the clarification—it worked perfectly!
