### ISSUE TITLE
Issue Editing mailman-web Configuration

### ISSUE THREAD

**Issue by roddarjohn** [Shadowghost/mailcow-mailman3-dockerized#7]
Hi,

I am trying to get working with the REST API, which, to do so, it seems I must edit the Django configuration of mailman-web.

Their documentation ([found here](https://github.com/maxking/docker-mailman)) indicates that there should be a file called `settings_local.py` which is found in `/mailman/web/`.  I tried searching in `<path-to-repo>/data/mailman/` but came up blank.  I then searched in a few other directories (all those in `<path-to-repo>/data/`) but could not find anything.

If it would be possible to mess with these configuration files that would be amazing and/or interact with the REST API which I have as of yet been unable to use.

**Comment by Shadowghost** [comment]
You need to create this file manually, since the container is configured to load the **additional** configuration parameters from this config.

**Comment by roddarjohn** [comment]
So I should create the file in `<path-to-repo>/data/mailman/settings_local.py`?

**Comment by Shadowghost** [comment]
No you should edit `<path-to-repo>/data/mailman/web/settings_local.py`
