### ISSUE TITLE
Log Directory Question

### ISSUE THREAD

**Issue by roddarjohn** [Shadowghost/mailcow-mailman3-dockerized#8]
I am trying to find the logs for `mailcowdockerized_mailman-core_1` to find the logs for the REST API.

`docker-mailman` seems to indicate that the logs will be found at `/opt/mailman/core/var/logs/mailman.log`.  I go to `<path-to-repo>/data/mailman/` but there is no `core` directory in that location.

Thoughts?

**Comment by Shadowghost** [comment]
The files for mailman core reside inside the docker volume `mailman-core-vol-1`. Should be something like `mailcowdockerized_mailman-core-vol-1` on this setup. You should be able to directly access it at `/var/lib/docker/volumes/mailcowdockerized_mailman-core-vol-1/_data` or somthing similar.
